app:
  debug: yes
  http_port: 8080
  log_level: 2

log:
  location: logs
  console: true
  syslog: false
  slack_enabled: no
  slack_webhook: https://hooks.slack.com/services/...

database:
  main:
    name: test
    address: 127.0.0.1:3306
    username: test
    password: test
    max_open_connections: 5
    max_idle_connections: 1
    max_lifetime: 300

proxy:
  enabled: no
  address: http://127.0.0.1:8080